# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque}
  s.version = "1.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath"]
  s.date = %q{2010-03-04}
  s.description = %q{}
  s.email = %q{chris@ozmm.org}
  s.executables = ["resque", "resque-web"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     ".kick",
     "CONTRIBUTORS",
     "HISTORY.md",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "bin/resque",
     "bin/resque-web",
     "config.ru",
     "deps.rip",
     "examples/async_helper.rb",
     "examples/demo/README.markdown",
     "examples/demo/Rakefile",
     "examples/demo/app.rb",
     "examples/demo/config.ru",
     "examples/demo/job.rb",
     "examples/god/resque.god",
     "examples/god/stale.god",
     "examples/instance.rb",
     "examples/simple.rb",
     "init.rb",
     "lib/resque.rb",
     "lib/resque/errors.rb",
     "lib/resque/failure.rb",
     "lib/resque/failure/base.rb",
     "lib/resque/failure/hoptoad.rb",
     "lib/resque/failure/multiple.rb",
     "lib/resque/failure/redis.rb",
     "lib/resque/helpers.rb",
     "lib/resque/job.rb",
     "lib/resque/server.rb",
     "lib/resque/server/public/idle.png",
     "lib/resque/server/public/jquery-1.3.2.min.js",
     "lib/resque/server/public/jquery.relatize_date.js",
     "lib/resque/server/public/poll.png",
     "lib/resque/server/public/ranger.js",
     "lib/resque/server/public/reset.css",
     "lib/resque/server/public/style.css",
     "lib/resque/server/public/working.png",
     "lib/resque/server/views/error.erb",
     "lib/resque/server/views/failed.erb",
     "lib/resque/server/views/key_sets.erb",
     "lib/resque/server/views/key_string.erb",
     "lib/resque/server/views/layout.erb",
     "lib/resque/server/views/next_more.erb",
     "lib/resque/server/views/overview.erb",
     "lib/resque/server/views/queues.erb",
     "lib/resque/server/views/stats.erb",
     "lib/resque/server/views/workers.erb",
     "lib/resque/server/views/working.erb",
     "lib/resque/stat.rb",
     "lib/resque/tasks.rb",
     "lib/resque/version.rb",
     "lib/resque/worker.rb",
     "tasks/redis.rake",
     "tasks/resque.rake",
     "test/redis-test.conf",
     "test/resque_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb"
  ]
  s.homepage = %q{http://github.com/defunkt/resque}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{}
  s.test_files = [
    "test/resque_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb",
     "examples/async_helper.rb",
     "examples/demo/app.rb",
     "examples/demo/job.rb",
     "examples/instance.rb",
     "examples/simple.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<redis-namespace>, [">= 0"])
      s.add_runtime_dependency(%q<vegas>, [">= 0.1.2"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<redis-namespace>, [">= 0"])
      s.add_dependency(%q<vegas>, [">= 0.1.2"])
      s.add_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<redis-namespace>, [">= 0"])
    s.add_dependency(%q<vegas>, [">= 0.1.2"])
    s.add_dependency(%q<sinatra>, [">= 0.9.2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

